apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: default
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.0.1-runtime-ubuntu22.04  # Using a CUDA-enabled base image
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    command: ["sleep","infinity"] # run nvidia-smi
  restartPolicy: Never
