apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: default
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.0.1-runtime-ubuntu22.04  # Using a CUDA-enabled base image
    resources:
      limits:
        nvidia.com/gpu: 1  # Request one GPU
    command: ["nvidia-smi"]
  restartPolicy: Never
