apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: default
spec:
  containers:
  - name: main
    image: cyberdog123/pytorch_gpu_utilizer # or nvidia/cuda:12.0.1-runtime-ubuntu22.04 for no utilization test
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
#  nodeSelector:
#    kubernetes.io/hostname: worker01
