apiVersion: v1
kind: Pod
metadata:
  name: node-debug-shell
spec:
  nodeName: <TARGET_NODE_NAME>
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
    - name: node-debug-shell
      image: docker.io/alpine:3.13
      command:
        - nsenter
      args:
        - "-t"
        - "1"
        - "-m"
        - "-u"
        - "-i"
        - "-n"
        - sleep
        - "14000"
      securityContext:
        privileged: true
