apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-4gpu-devices-10gb-mem-each
  namespace: runai-test
  labels:
    app: test-4gpu-devices-10gb-mem-each
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-4gpu-devices-10gb-mem-each
  template:
    metadata:
      labels:
        app: test-4gpu-devices-10gb-mem-each
      annotations:
        gpu-fraction-num-devices: "4"
        gpu-memory: "10000"
    spec:
      schedulerName: runai-scheduler
      containers:
      - name: pytorch
        image: nvcr.io/nvidia/pytorch:25.03-py3
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80
