apiVersion: apps/v1
kind: Deployment
metadata:
  name: itay-deploy-wow
  namespace: runai-zzz # 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itay-deploy-wow
  template:
    metadata:
      labels:
        app: itay-deploy-wow
    spec:
      containers:
        - resources:
            limits:
              nvidia.com/gpu: 1
          image: nginx
          command:
          - sleep
          - infinity
          imagePullPolicy: Always
          name: itay-deploy-wow
      schedulerName: runai-scheduler
